// Every demo uses one project and scripted state. No network calls or user data.
export function Robin(extra=''){return `<svg class="robin ${extra}" viewBox="0 0 44 52" role="img" aria-label="Robin"><path d="M9 44C3 34 7 12 20 7C34 2 39 20 37 34L41 44Z" fill="#41423d"/><path d="M21 25C33 21 36 30 34 42C28 49 14 46 13 38C12 33 15 28 21 25Z" fill="#bb594a"/><circle cx="29" cy="18" r="2" fill="white"/><path d="M35 20L43 23L36 26Z" fill="#b39359"/><path d="M10 28Q7 36 17 39" fill="#56564e"/></svg>`}
const brand=`<a class="brand" href="#"><span class="brand-icon">k<span>•</span></span><strong>知更 KnowMore</strong></a>`;
export function Sidebar(campus=false){return `<aside class="sidebar">${brand}<div class="side-item">＋ &nbsp; 新建 Project</div><div class="side-item">▧ &nbsp; 资料库</div><div class="side-item">✧ &nbsp; 灵感</div><div class="side-heading">${campus?'COURSE CONTEXT':'PROJECTS'}</div><div class="side-item selected">⌑ &nbsp; AI 与高等教育</div><div class="side-item side-indent">▤ &nbsp; ${campus?'Critical Reflection #2':'Assignment'}</div><div class="side-item side-indent">▧ &nbsp; Reading B</div><div class="side-item side-indent">≡ &nbsp; Field Notes</div><div class="side-item side-indent idea-on">✧ &nbsp; Idea #03 <span style="margin-left:auto;color:#b68d22">•</span></div><div class="side-item side-indent">▤ &nbsp; Draft</div>${campus?'<div class="side-heading">OCT 28 · 23:59</div><div class="side-item">☷ &nbsp; Rubric</div>':'<div class="side-heading">YOUR SPACE</div><div class="side-item">⌑ &nbsp; CHI Proposal</div><div class="side-item">⌑ &nbsp; Design Reflection</div>'}<div class="side-bottom"><span class="avatar">L</span> Lin 的工作空间 <span>⌄</span></div></aside>`}
export const tabs=['Canvas','Map','Document','Production','Review'];
function toolbar(active='Document'){return `<div class="work-toolbar"><span>AI 与高等教育 <span style="color:#c1c1b7"> / </span> Draft</span><div class="toolbar-tools"><span>↶</span><span>◷</span><span>分享 ↗</span><span>···</span></div></div><div class="mode-bar"><div class="mode-tabs">${tabs.map(t=>`<button data-mode="${t}" class="${t===active?'active':''}" aria-pressed="${t===active}">${t}</button>`).join('')}</div><span class="save-state">✓ 已保存所有更改</span></div>`}
export function documentView(){return `<article class="editor"><div class="doc-meta">CRITICAL REFLECTION &nbsp; / &nbsp; DRAFT 02</div><h3>AI 如何提高学习，而不是替代学习？</h3><p>当 AI 可以在几秒内生成一篇结构完整的文章，我们需要重新追问：<br>学习的价值，究竟在于获得答案，还是形成判断的过程？</p><h4>01 &nbsp; 从「提供答案」到「支持思考」</h4><p>真正有价值的 AI 支持，不应只是缩短完成任务的时间。<mark>它应该帮助学习者建立自己的理解，在关键时刻提出问题，而不是提前结束思考。</mark></p><p>这意味着，我们需要区分学习中的 agency 与 assistance。工具可以参与过程，但学习者应始终保有作出判断的空间。</p><p class="source-foot">↳ &nbsp; Reading B · p.14 &nbsp; · &nbsp; Idea #03 &nbsp; · &nbsp; Field Note #03</p><div class="inline-tools"><span>✧ Challenge</span><span>Evidence</span><span>Clarify</span><span>···</span></div></article>`}
export function shell(content,active='Document',campus=false){return `<div class="window-title"><span class="traffic"><i></i><i></i><i></i></span><span>知更 KnowMore &nbsp; / &nbsp; ${campus?'Campus':'Personal'}</span><span>↗</span></div><div class="window-body">${Sidebar(campus)}<div class="work-main">${toolbar(active)}${content}</div></div>`}
document.querySelector('#hero-demo').innerHTML=shell(documentView()+`<div class="robin-note hero-note"><div class="note-copy"><b>ROBIN · CONNECT</b>这个观点和你 Canvas 阶段的<br>Idea #03 有关联。</div>${Robin()}</div>`);
// Main narrative and secondary demos are loaded as a separate local module.
import('./story.js');
