import {Robin, shell, documentView, tabs} from './app.js';
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const stages=[
 {label:'01 / CAPTURE',title:'灵感刚出现时，<br>不需要马上写成一篇文章。',copy:'摘录一段阅读，留下一个问题，让想法自由发生。再用一条线，把原本散落的材料连接起来。',note:'你是在表达证据关系，还是它让你产生了联想？',verb:'Organize →'},
 {label:'02 / CONNECT',title:'当想法开始变多，<br>帮它们找到结构。',copy:'同一组材料，换一种看法。让证据支撑观点，也让尚未被回答的问题保持可见。',note:'Argument B 目前只有观点。哪一条材料可以支持它？',verb:'Start Writing →'},
 {label:'03 / CREATE',title:'灵感不应该，<br>在进入作品时消失。',copy:'节点成为大纲，大纲成为正文。每一个论点，仍然能找到它最初的想法和来源。',note:'这个观点来自 Idea #03。要不要回到当时的 Field Note？',verb:'Convert to LaTeX →'},
 {label:'04 / PRODUCE',title:'从最初一张便签，<br>一直到最终 PDF。',copy:'从表达切换到排版。引用、公式和图表进入最终作品，思考的来路依然保留。',note:'Figure 1 已加入正文引用。来源与修改历史也一并保留。',verb:'Review →'},
 {label:'05 / REFLECT',title:'作品完成了，<br>思考的过程也值得留下。',copy:'回看一个想法如何被挑战、展开和修改。最终作品之外，还有属于你的学习过程。',note:'结论还可以更明确地回应开头的 Thesis。最后的判断交给你。',verb:'重新播放 ↺'}];
const nodes=[{id:'reading',type:'READING B · P.14',title:'支持学习，而非替代思考',body:'“有效的支架，应该随着学习者能力的发展逐步撤去。”',tag:'Source · 课程阅读'}, {id:'idea',type:'MY IDEA #03',title:'把「效率」换成「参与感」？',body:'如果 AI 不是替我完成，而是帮我继续想下去。',tag:'Idea · 由你提出'}, {id:'field',type:'FIELD NOTE #03',title:'答案出现之后，讨论停止了。',body:'课堂观察：直接给出结果，可能让探索过早结束。',tag:'Observation · 周二 14:30'}, {id:'argument',type:'ARGUMENT B',title:'保留学习者的主动权',body:'支持应该发生在关键节点，而不是覆盖整个过程。',tag:'Open question · 需要证据'}];
const nodeMarkup=nodes.map(n=>`<div class="graph-node node-${n.id}" data-id="${n.id}"><div class="node-type">${n.type}</div><h4>${n.title}</h4><p>${n.body}</p><small>${n.tag}</small></div>`).join('');
const production=`<div class="production-surface"><div class="latex"><div class="pane-label">main.tex <span>LaTeX source</span></div><pre><i>01</i> <em>\\documentclass</em>{article}
<i>02</i> <em>\\usepackage</em>{ctex}
<i>03</i> <em>\\title</em>{AI 与学习者的主动权}
<i>04</i> <em>\\begin</em>{document}
<i>05</i> <em>\\maketitle</em>
<i>06</i>
<i>07</i> <em>\\section</em>{支持思考，而非替代}
<i>08</i> AI 应帮助学习者建立自己的理解，
<i>09</i> 而不是提前结束思考。
<i>10</i> <em>\\cite</em>{readingB}
<i>11</i>
<i>12</i> <em>\\begin</em>{equation}
<i>13</i> L = A + R
<i>14</i> <em>\\end</em>{equation}
<i>15</i>
<i>16</i> <em>\\begin</em>{figure}
<i>17</i> <em>\\caption</em>{学习支持的连续过程}
<i>18</i> <em>\\label</em>{fig:process}
<i>19</i> <em>\\end</em>{figure}
<i>20</i> 如图 <em>\\ref</em>{fig:process} 所示。
<i>21</i> <em>\\end</em>{document}</pre><div class="compile-state">✓ PDF 预览已更新 <span>演示渲染</span></div></div><div class="pdf-pane"><div class="pane-label">Final.pdf <span>1 / 3 &nbsp; − &nbsp; 100% &nbsp; ＋</span></div><article class="pdf-paper"><small>CRITICAL REFLECTION #2</small><h3>AI 与学习者的主动权</h3><p class="pdf-author">Lin · AI & Education</p><h4>摘要</h4><p>本文探讨生成式 AI 在高等教育中的参与方式，主张以支持自主思考为核心，重新设计人机协作的边界。</p><h4>1 &nbsp; 支持思考，而非替代</h4><p>AI 应帮助学习者建立自己的理解，而不是提前结束思考。有效的支持需要随学习阶段自然变化。<sup>[1]</sup></p><div class="formula">L = A + R <span>(1)</span></div><div class="pdf-figure">Idea <span>→</span> Structure <span>→</span> Artifact</div><small>Figure 1. 学习支持的连续过程</small><p>如图 1 所示，学习者在构建关系、组织证据与修订表达中，持续保有判断与选择的空间。</p><div class="pdf-page-number">1</div></article></div></div>`;
const review=`<div class="review-surface"><div class="review-head"><span class="doc-meta">REFLECTION / PROCESS PORTFOLIO</span><h3>每一步，都有来处。</h3><p>保留重要转折，而非每一次点击。</p></div><div class="process-line">${['Initial Note','Idea #03','Connection','Reframe','Outline','Draft','Revision','Final PDF'].map((n,i)=>`<div style="--order:${i}"><span>${String(i+1).padStart(2,'0')}</span><b>${n}</b></div>`).join('')}</div><div class="review-summary"><div><small>最初的问题</small><p>AI 如何帮助我们更快地完成作业？</p></div><span>↘</span><div><small>最终的主张</small><p>AI 如何支持学习者保有思考的主动权？</p></div></div><div class="review-evidence">↳ 关联保留：4 份资料 · 3 次主要修订 · 1 个最终作品 <span>预设项目</span></div></div>`;
document.querySelector('#story-content').innerHTML=`
<section class="section bridge center"><div class="section-label">ONE PROJECT. EVERY STAGE.</div><h2>思考不会直线前进。<br>工作空间也不应该只有一种形态。</h2><p class="section-intro">从散落的片段，到清晰的结构，再到值得分享的作品。<br>界面跟随你变化，资料、想法和每一次修改始终相连。</p><div class="stage-track">${tabs.map((s,i)=>`<a href="#workspace" data-jump="${i}"><span>0${i+1}</span>${s}</a>`).join('<i>↗</i>')}</div></section>
<section id="workspace" class="workspace-section"><div class="section stage-heading"><div><div class="section-label" id="stage-label"></div><h2 id="stage-title"></h2></div><div class="stage-description"><p id="stage-copy" class="section-intro"></p><div class="play-controls"><button id="play-toggle" aria-label="暂停自动演示">Ⅱ 暂停演示</button><button id="replay" aria-label="重新播放演示">↺ 重播</button><span id="stage-count">01 / 05</span></div></div></div><div class="stage-window-wrap"><div id="stage-demo" class="product-window">${shell(`<div class="adaptive-surface stage-0" id="adaptive"><svg class="connections" viewBox="0 0 860 490" preserveAspectRatio="none" aria-hidden="true"><path class="line-primary" d="M250 150 C380 150 350 235 470 235"/><path class="line-secondary" d="M260 355 C400 355 400 255 470 255"/><path class="line-third" d="M625 235 C740 235 730 385 630 385"/></svg><span class="connection-label">inspires</span>${nodeMarkup}<div class="graph-caption">AI 如何提高学习，而不是替代学习？</div><div class="document-surface">${documentView()}<button class="provenance-marker" aria-label="查看段落来源">⌘<span>Derived from<br><b>Idea #03</b><br>Reading B · p.14<br>Field Note #03<br>Robin Challenge #07</span></button><div class="revision"><span class="revision-old">AI 能提高学习效率。</span> <mark>AI 应支持学习者作出自己的判断。</mark> <button data-revision="accept" aria-label="接受修改">✓</button><button data-revision="reject" aria-label="拒绝修改">×</button></div></div>${production}${review}<div class="robin-note stage-note"><div class="note-copy"><b>ROBIN · <span id="robin-role">CREATIVE PARTNER</span></b><span id="stage-note"></span></div>${Robin()}</div><div class="canvas-toolset" aria-label="画布工具示意"><span>↖</span><span>✎</span><span>▢</span><span>T</span><span>⌁</span><span>⊕</span></div><div class="canvas-zoom">− &nbsp; 100% &nbsp; ＋</div></div>`,'Canvas')}</div><div class="stage-bottom"><span><span class="yellow-dot"></span> 同一 Project · Sources、Ideas 与 History 始终保留</span><button id="stage-next">Organize →</button></div></div></section>
<section id="robin" class="section ambient-section"><div class="ambient-copy"><div class="section-label">A QUIET INTELLIGENCE</div><h2>理解你的现场，<br>也懂得留一点空间。</h2><p class="section-intro">Robin 不需要一直占据一个聊天窗口。<br>当你需要新的角度、一条证据，或一点提醒，<br>它恰好在这里。</p><p class="handwritten">Let Robin come to you.</p><div class="ambient-steps"><span>01 探头</span><span>02 轻声提醒</span><span>03 按需展开</span></div></div><div class="ambient-demo"><div class="pane-label">Draft / 讨论 <span>✓ 已保存</span></div><div class="ambient-editor"><small>02 &nbsp; AGENCY & ASSISTANCE</small><h3>让问题，保持开放。</h3><p>给予学习者完整的答案，可能会带来即时的满足。但长期来看，<mark>这种便利是否真正转化为理解？</mark></p><p>我们需要将注意力，从生成结果转向学习过程中发生的判断。</p><div class="quiet-line"></div><div class="quiet-line short"></div></div><button class="peek-button" id="peek" aria-label="查看 Robin 的发现">${Robin()}</button><div class="peek-bubble">这里可能缺一个来源。</div><div class="ambient-detail" hidden><span class="section-label">ROBIN · EVIDENCE</span><p>Reading B 第 14 页讨论了“学习支架”。它可以支持这里的判断，但还需要说明它与你的课堂观察有什么联系。</p><button id="close-note">知道了，继续写作 ↗</button></div></div></section>
<hr class="section-rule"><section class="section memory-section"><div class="memory-demo" id="memory-demo"><div class="pane-label">Personal <span>SCENE MEMORY</span></div><div class="recent-projects"><small>WELCOME BACK, LIN</small><h3>继续你的现场。</h3><button id="resume-project"><span><b>AI 与高等教育</b><small>上次停在「Agency 与 Assistance」</small></span><span>↗</span></button><div class="recent-row"><span>CHI Proposal</span><small>2 个 Idea 尚未展开</small></div><div class="recent-row"><span>Design Reflection</span><small>Drafting</small></div></div><div class="resumed-scene"><div class="resume-source">SOURCE OPEN<br><b>Reading B · p.14</b><p>有效的学习支架，随能力的发展逐步撤去。</p><span>SELECTED · Idea #03</span></div><div class="resume-editor"><small>恢复至上次编辑位置</small><h3>Agency 与 Assistance</h3><p>工具可以参与过程，<mark>但学习者应始终保有作出判断的空间。</mark><span class="caret"></span></p><span class="resume-status">${Robin()} 我们上次停在这里。</span><button id="memory-reset">↶ 返回最近项目</button></div></div></div><div><div class="section-label">PERSISTENT SCENE</div><h2>回来时，<br>不用重新进入状态。</h2><p class="section-intro">上次打开的资料、选中的想法、写到一半的段落。<br>不只保存文件，也保存你正在思考的现场。</p><div class="memory-tags"><span>Sources</span><span>Selected idea</span><span>Scroll position</span><span>Revision history</span></div></div></section>
<section id="campus" class="campus-section"><div class="section center campus-heading"><div class="section-label">KNOWMORE CAMPUS</div><h2>当同一个工作现场，<br>进入真实课程。</h2><p class="section-intro">让 AI 真正进入教学，而不是绕过教学。</p><div class="teacher-questions"><span>禁 AI，还是完全开放 AI？</span><span>作品很好，学生真的学会了吗？</span><span>如何让反馈进入每个人的学习过程？</span></div><p class="campus-statement">教师需要的，是<span>设计 AI 如何参与学习。</span></p></div><div class="campus-content"><div class="campus-navigation" role="tablist" aria-label="校园版演示"><button class="active" data-campus="student" role="tab" aria-selected="true">01 学生工作现场</button><button data-campus="policy" role="tab" aria-selected="false">02 教学策略</button><button data-campus="submission" role="tab" aria-selected="false">03 过程与提交</button><button data-campus="review" role="tab" aria-selected="false">04 教师评阅</button></div><div class="product-window campus-window" id="campus-demo"></div><div class="campus-caption" id="campus-caption"></div></div></section>
<section class="section insights-section"><div><div class="section-label">LEARNING INSIGHTS</div><h2>看见共同的困难，<br>把洞察带回教学。</h2><p class="section-intro">聚合的学习线索，帮助教师调整下一次课堂。<br>不把学习简化成一个 AI 使用比例。</p><small class="demo-label">以下为情境示例，不代表真实教学统计。</small></div><div class="insights-list"><div><span>01</span><p><b>证据如何进入论证？</b>多份作品在 Evidence Integration 环节需要进一步支持。</p></div><div><span>02</span><p><b>还有没有别的可能？</b>一些想法在初期便迅速收敛，值得增加发散讨论。</p></div><div><span>03</span><p><b>把挑战转化为修改。</b>回看 Challenge 如何触发新的角度与后续修订。</p></div></div></section>
<hr class="section-rule"><section class="section robin-tech center"><div class="section-label">ROBIN LEARNING INTELLIGENCE</div><h2>不只是「如何回答」。<br>而是「现在应该怎样帮助？」</h2><p class="section-intro">理解你正在做什么、做到哪里，以及什么应该留给你自己。<br>帮助的方式，来自对现场的理解。</p><div class="intelligence-flow"><div class="context-inputs"><span>Current Scene</span><span>Project Context</span><span>Existing Work</span><span>Current Stage</span><span>User / Teacher Policy</span><span>Long-term Memory</span></div><div class="flow-stem"></div><div class="robin-core">${Robin()}<div><strong>Robin</strong><small>Intervention Strategy</small></div></div><div class="flow-stem"></div><div class="interventions"><span>Question</span><span>Challenge</span><span>Connect</span><span>Suggest</span><span>Generate</span></div></div></section>
<section id="vision" class="section ecosystem"><div class="section-label">ONE CORE. TWO WORLDS. ONE ROBIN.</div><h2>缘起红鸟，<br>但不止于校园。</h2><div class="editions"><div><span class="edition-number">01 / PERSONAL</span><h3>你的想法，值得一个现场。</h3><p>阅读、研究、创作。从零散材料到自己的作品，<br>让持续思考成为每天自然发生的事。</p><div class="edition-values"><span>用户价值</span><span>真实使用</span><span>产品增长</span></div></div><div><span class="edition-number">02 / CAMPUS</span><h3>让学习，真正发生。</h3><p>将课程目标、教师策略与评价标准带入现场，<br>探索有边界、可反思的 AI 学习方式。</p><div class="edition-values"><span>教学深度</span><span>课程 Context</span><span>教育验证</span></div></div></div><div class="shared-core"><span>Personal</span><i></i><b>${Robin()} Shared workspace · Robin Intelligence</b><i></i><span>Campus</span></div></section>
<section class="section features"><div class="section-label">THE DETAILS THAT KEEP YOU IN FLOW</div><h2>让思考继续的小事，<br>我们也放在心上。</h2><div class="feature-grid">${[['01','多种材料，同一个 Project','阅读、摘录、图片与灵感，不必在不同工具间反复搬运。'],['02','每个观点，都有来处','从段落回到 Source 与 Idea，看见你的证据与推理。'],['03','记住现场，而不只是文件','恢复上下文，让昨天的思考自然接上今天。'],['04','修改留下痕迹','保留关键 Revision，也保留改变判断的理由。'],['05','让空间适应思考','Canvas、Map、Document、Production 自然接续。'],['06','从个人，到真实课程','共享一套内核，在 Campus 中加入教学目标与边界。']].map(([n,t,p])=>`<article><span>${n}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section>
<section class="section ending center"><p class="section-label">留一点空间，给下一个正在发生的想法。</p><h2>从一个现场开始。</h2><p class="section-intro">知更 KnowMore<br>从资料到想法，再到作品，一个地方完成。</p><div class="hero-actions"><a class="button" href="#workspace">体验 KnowMore Demo <span>↗</span></a><a class="text-link" href="#campus">了解 Campus <span>→</span></a></div><div class="powered">${Robin()} Powered by Robin</div></section>`;

const adaptive=document.querySelector('#adaptive'),stageWindow=document.querySelector('#stage-demo');let current=0,elapsed=0,playing=!reduced.matches,visible=false,last=0;
function setStage(index){current=index;elapsed=0;const s=stages[index];adaptive.className=`adaptive-surface stage-${index}`;document.querySelector('#stage-label').textContent=s.label;document.querySelector('#stage-title').innerHTML=s.title;document.querySelector('#stage-copy').textContent=s.copy;document.querySelector('#stage-note').textContent=s.note;document.querySelector('#stage-next').textContent=s.verb;document.querySelector('#stage-count').textContent=`0${index+1} / 05`;document.querySelector('#robin-role').textContent=['CREATIVE PARTNER','EVIDENCE GAP','CONNECT','PRODUCTION','REFLECT'][index];stageWindow.querySelectorAll('[data-mode]').forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-pressed',i===index)});document.querySelector('.stage-note').classList.remove('visible');adaptive.classList.remove('connected','labeled');if(reduced.matches){adaptive.classList.add('connected','labeled');document.querySelector('.stage-note').classList.add('visible')} }
function syncPlayback(){document.querySelector('#play-toggle').textContent=playing?'Ⅱ 暂停演示':'▷ 播放演示';document.querySelector('#play-toggle').setAttribute('aria-label',playing?'暂停自动演示':'播放自动演示');adaptive.classList.toggle('paused',!playing)}
setStage(0);syncPlayback();
document.querySelector('#play-toggle').onclick=()=>{playing=!playing;syncPlayback()};
document.querySelector('#replay').onclick=()=>{setStage(0);playing=true;syncPlayback()};
document.querySelector('#stage-next').onclick=()=>setStage((current+1)%5);
stageWindow.querySelectorAll('[data-mode]').forEach((b,i)=>b.onclick=()=>{setStage(i);playing=false;syncPlayback();adaptive.classList.add('connected','labeled');document.querySelector('.stage-note').classList.add('visible')});
document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>setStage(Number(b.dataset.jump)));
document.querySelectorAll('#hero-demo [data-mode]').forEach((b,i)=>b.onclick=()=>{setStage(i);document.querySelector('#workspace').scrollIntoView({behavior:reduced.matches?'instant':'smooth'})});
new IntersectionObserver(entries=>{visible=entries[0].isIntersecting},{threshold:.25}).observe(stageWindow);
function tick(t){const dt=last?Math.min(t-last,100):0;last=t;if(visible&&playing&&!document.hidden){elapsed+=dt;if(elapsed>900)adaptive.classList.add('connected');if(elapsed>2200)document.querySelector('.stage-note').classList.add('visible');if(elapsed>4800)adaptive.classList.add('labeled');if(elapsed>8800)document.querySelector('.stage-note').classList.remove('visible');if(elapsed>11200)setStage((current+1)%5)}requestAnimationFrame(tick)}requestAnimationFrame(tick);
document.querySelectorAll('[data-revision]').forEach(b=>b.onclick=()=>{const row=b.closest('.revision');row.innerHTML=b.dataset.revision==='accept'?'<mark>AI 应支持学习者作出自己的判断。</mark> <small>✓ 修改已接受</small>':'AI 能提高学习效率。 <small>已保留原文</small>'});
const ambient=document.querySelector('.ambient-demo');document.querySelector('#peek').onclick=()=>{ambient.querySelector('.ambient-detail').hidden=false;ambient.classList.add('expanded')};document.querySelector('#close-note').onclick=()=>{ambient.querySelector('.ambient-detail').hidden=true;ambient.classList.remove('expanded')};
const memory=document.querySelector('#memory-demo');let memoryTimer,resetTimer;
function resume(){memory.classList.add('restored');clearTimeout(resetTimer);resetTimer=setTimeout(()=>memory.classList.add('settled'),2400)}
document.querySelector('#resume-project').onclick=resume;document.querySelector('#memory-reset').onclick=()=>{memory.classList.remove('restored','settled');clearTimeout(resetTimer)};
new IntersectionObserver(entries=>{if(entries[0].isIntersecting&&!reduced.matches){memoryTimer=setTimeout(resume,2600)}else{clearTimeout(memoryTimer)}},{threshold:.6}).observe(memory);
new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('in-view',e.isIntersecting)),{threshold:.35}).observe(ambient);

const policyRows=[['Reading',['Explain','Compare','Connect']],[ 'Initial Ideation',['Question','Challenge','Generate Example','Full Outline']],['Draft',['Feedback','Evidence','Local Rewrite','Paragraph Generation']],['Production',['Citation','Formatting','LaTeX']],['Final',['Course Policy']]];
let campusTab='student',reviewTab='Final';const policyState={ 'Generate Example':'limited','Full Outline':'off','Paragraph Generation':'limited'};const selectedEvidence=new Set(['Initial Ideas','Major Revision','Sources Used','Reflection']);let submitted=false;
const campus=document.querySelector('#campus-demo');
function campusBody(){if(campusTab==='student')return documentView()+`<div class="course-policy-note">${Robin()}<div><b>这门课程中，Robin 会先提问，再给建议。</b><span>当前阶段：Draft · 可以反馈与局部修改，整段生成需说明。</span></div></div>`;
if(campusTab==='policy')return `<div class="policy-content"><div class="doc-meta">CRITICAL REFLECTION #2 / TEACHER VIEW</div><h3>AI Learning Policy</h3><p class="subtle">设计每个阶段的帮助方式。点击可切换：允许 → 有条件 → 不开放。</p><div class="policy-rows">${policyRows.map(([phase,actions])=>`<div class="policy-row"><b>${phase}</b><div>${actions.map(a=>{const s=policyState[a]||'on';return `<button class="policy-chip ${s}" data-policy="${a}" aria-label="${a}：${s==='on'?'允许':s==='limited'?'有条件':'不开放'}">${s==='on'?'✓':s==='limited'?'△':'×'} ${a}</button>`}).join('')}</div></div>`).join('')}</div><div class="policy-feedback" aria-live="polite">${Robin()}<span>Robin 会按这份课程策略调整支持方式。</span></div></div>`;
if(campusTab==='submission')return `<div class="submission-content"><div class="doc-meta">SUBMISSION / STUDENT VIEW</div><h3>让过程透明，让私人空间保留。</h3><p class="subtle">提交前，你可以清楚看见老师将收到什么。</p><div class="submission-columns"><div><h4>随 Assignment 提交</h4><div class="final-file">▤ &nbsp; Final.pdf <small>最终作品 · 必选</small></div>${['Initial Ideas','Major Revision','Sources Used','Reflection'].map(a=>`<label><input type="checkbox" data-evidence="${a}" ${selectedEvidence.has(a)?'checked':''}> ${a}</label>`).join('')}</div><div class="private-column"><h4>保持 Private <span>⌑</span></h4><p>Personal Notes</p><p>Unsubmitted Ideas</p><p>Private Robin Chat</p><small>私人内容不会出现在提交包中。</small></div></div><div class="submit-actions"><button class="button small" id="submit-demo">${submitted?'✓ 已完成模拟提交':'预览并模拟提交 ↗'}</button><span id="submit-status" aria-live="polite">${submitted?`Final.pdf 与 ${selectedEvidence.size} 项过程证据已打包（演示）`:'仅演示，不向任何人发送内容'}</span></div></div>`;
return `<div class="teacher-review"><div class="teacher-review-tabs" role="tablist" aria-label="评阅内容">${['Final','Process','Sources','AI Use'].map(t=>`<button role="tab" aria-selected="${reviewTab===t}" class="${reviewTab===t?'active':''}" data-review="${t}">${t}</button>`).join('')}</div><div class="teacher-review-grid"><article><small>STUDENT ARTIFACT · LIN</small>${reviewTab==='Final'?'<h3>AI 与学习者的主动权</h3><p>真正有价值的 AI 支持，不应只是缩短完成任务的时间。它应该帮助学习者建立自己的理解。</p><h4>结论</h4><p>工具的价值，应在持续思考的过程中被理解与检验。</p>':reviewTab==='Process'?'<h3>重要转折</h3><p>Initial Idea → 以效率为目标</p><p>Robin Reframe → 关注学习参与感</p><p>Major Revision → 区分 agency 与 assistance</p><p>Final → 学生形成自己的主张</p>':reviewTab==='Sources'?'<h3>Sources used</h3><p>Reading B · p.14<br><small>支持：学习支架与自主性</small></p><p>Field Note #03<br><small>关联：答案出现后讨论停止</small></p><p>Lecture 06<br><small>背景：Agency & Assistance</small></p>':'<h3>AI 如何参与</h3><p>Initial Ideation：主要由学生完成。</p><p>Robin：提供 2 次 Reframe。</p><p>Draft：使用 Evidence Assistance。</p><p>Final Thesis：与 Robin Suggestion 不同。</p>'}</article><div class="rubric-column"><small>COURSE RUBRIC</small><h4>Argument <span>30</span></h4><p>核心主张与论证结构</p><h4>Evidence <span>25</span></h4><p>证据的关联与整合</p><h4>Critical Reflection <span>25</span></h4><p>对自身假设的反思</p><h4>Clarity <span>20</span></h4><p>表达与组织的清晰度</p></div><div class="pre-review"><small>ROBIN · PRELIMINARY REVIEW</small><h4>Argument <span>较强</span></h4><p>Thesis 清晰，主要段落围绕核心问题展开。</p><p class="review-alert">关注：Conclusion 尚未完全回应 Thesis。</p><h4>Evidence <span>需加强</span></h4><p>Paragraph 4 的核心 Claim 缺少课程来源。</p><small>Rubric-aligned Review<br>辅助教师判断，不自动评分。</small></div></div></div>`}
function renderCampus(){campus.innerHTML=shell(campusBody(),'Document',true);campus.querySelector('.mode-tabs').innerHTML='<span class="course-badge">COURSE PROJECT</span>';campus.querySelector('.save-state').textContent='AI & Education · Oct 28, 23:59';document.querySelector('#campus-caption').textContent=({student:'同一个工作空间，多一层课程语境。Assignment、Materials、Rubric 与 Robin 一起进入现场。',policy:'从“允不允许 AI”，走向“在什么时候，以什么方式支持学习”。',submission:'提交作品与重要过程证据，私人笔记和未提交的想法留在自己手中。',review:'作品、评价标准与初步反馈并排呈现。教学判断始终由教师作出。'})[campusTab];campus.querySelectorAll('[data-policy]').forEach(b=>b.onclick=()=>{const a=b.dataset.policy;policyState[a]=({on:'limited',limited:'off',off:'on'})[policyState[a]||'on'];renderCampus();campus.querySelector(`[data-policy="${a}"]`).focus();campus.querySelector('.policy-feedback span').textContent=`${a} 已设为「${policyState[a]==='on'?'允许':policyState[a]==='limited'?'有条件支持':'不开放'}」，Robin 将遵循此策略。`});campus.querySelectorAll('[data-evidence]').forEach(c=>c.onchange=()=>{c.checked?selectedEvidence.add(c.dataset.evidence):selectedEvidence.delete(c.dataset.evidence);submitted=false;campus.querySelector('#submit-demo').textContent='预览并模拟提交 ↗';campus.querySelector('#submit-status').textContent=`将包含 Final.pdf 与 ${selectedEvidence.size} 项过程证据`});const submit=campus.querySelector('#submit-demo');if(submit)submit.onclick=()=>{submitted=true;renderCampus()};campus.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{reviewTab=b.dataset.review;renderCampus()})}
renderCampus();document.querySelectorAll('[data-campus]').forEach(b=>b.onclick=()=>{campusTab=b.dataset.campus;document.querySelectorAll('[data-campus]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b)});renderCampus()});
// Arrow keys follow the visible tab order; Tab remains available for all controls.
document.querySelectorAll('[role="tablist"]').forEach(list=>list.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const buttons=[...list.querySelectorAll('[role="tab"]')];let i=buttons.indexOf(document.activeElement);if(i<0)return;e.preventDefault();i=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[i].click();buttons[i].focus()}));
// The Campus story also advances without requiring visitors to operate the UI.
let campusVisible=false,campusAuto=!reduced.matches,campusElapsed=0;
const campusPlay=document.createElement('button');campusPlay.className='campus-play';campusPlay.textContent=campusAuto?'Ⅱ 暂停校园演示':'▷ 播放校园演示';document.querySelector('.campus-caption').after(campusPlay);
function campusPlayLabel(){campusPlay.textContent=campusAuto?'Ⅱ 暂停校园演示':'▷ 播放校园演示'}
campusPlay.onclick=()=>{campusAuto=!campusAuto;campusElapsed=0;campusPlayLabel()};
new IntersectionObserver(e=>{campusVisible=e[0].isIntersecting},{threshold:.45}).observe(campus);
document.querySelector('.campus-navigation').addEventListener('click',e=>{if(e.target.closest('button')){campusAuto=false;campusPlayLabel()}});
campus.addEventListener('click',()=>{campusAuto=false;campusPlayLabel()});
setInterval(()=>{if(!campusVisible||!campusAuto||document.hidden)return;campusElapsed+=500;if(campusElapsed<12000)return;campusElapsed=0;const order=['student','policy','submission','review'];campusTab=order[(order.indexOf(campusTab)+1)%order.length];renderCampus();document.querySelectorAll('[data-campus]').forEach(b=>{const selected=b.dataset.campus===campusTab;b.classList.toggle('active',selected);b.setAttribute('aria-selected',selected)})},500);
